/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataComparisionPackage;

/**
 *
 * @author Jaswant
 */
public class screenTwoDCFrame extends javax.swing.JFrame {

    /**
     * Creates new form screenTwoDCFrame
     */
    public screenTwoDCFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        screenTwoDCSplitPane = new javax.swing.JSplitPane();
        dcleftPanel = new javax.swing.JPanel();
        dcrightPanel = new javax.swing.JPanel();

        setTitle("Data Comparision Window");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.lightGray);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        screenTwoDCSplitPane.setDividerLocation(150);

        dcleftPanel.setBackground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout dcleftPanelLayout = new javax.swing.GroupLayout(dcleftPanel);
        dcleftPanel.setLayout(dcleftPanelLayout);
        dcleftPanelLayout.setHorizontalGroup(
            dcleftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );
        dcleftPanelLayout.setVerticalGroup(
            dcleftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        screenTwoDCSplitPane.setLeftComponent(dcleftPanel);

        dcrightPanel.setBackground(new java.awt.Color(204, 204, 0));

        javax.swing.GroupLayout dcrightPanelLayout = new javax.swing.GroupLayout(dcrightPanel);
        dcrightPanel.setLayout(dcrightPanelLayout);
        dcrightPanelLayout.setHorizontalGroup(
            dcrightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
        );
        dcrightPanelLayout.setVerticalGroup(
            dcrightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        screenTwoDCSplitPane.setRightComponent(dcrightPanel);

        getContentPane().add(screenTwoDCSplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(screenTwoDCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(screenTwoDCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(screenTwoDCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(screenTwoDCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new screenTwoDCFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dcleftPanel;
    private javax.swing.JPanel dcrightPanel;
    private javax.swing.JSplitPane screenTwoDCSplitPane;
    // End of variables declaration//GEN-END:variables
}
