/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ScreenOne;
import DataComparisionPackage.*;
import QueryBuilderPackage.screenThreeQBFrame;
import java.io.File;
/**
 *
 * @author Jaswant
 */
public class screenOne extends javax.swing.JFrame {
 private screenTwoDCFrame jframeDCObj = null;
 private screenThreeQBFrame jframeQBObj = null;
 /**
     * Creates new form screenOne
     */
    public screenOne() {
        jframeDCObj = new screenTwoDCFrame();
           jframeQBObj = new screenThreeQBFrame();
        initComponents();
        startBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();
        descLb = new javax.swing.JLabel();
        startBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Choose the Data Comparision method");
        setMinimumSize(new java.awt.Dimension(800, 640));
        setPreferredSize(new java.awt.Dimension(1366, 786));

        jSplitPane1.setDividerLocation(270);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(1366, 786));

        leftPanel.setBackground(new java.awt.Color(0, 153, 255));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Data Comparision Utility");
        titleLabel.setToolTipText("");

        btnOne.setBackground(new java.awt.Color(102, 102, 102));
        btnOne.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnOne.setForeground(new java.awt.Color(255, 255, 255));
        btnOne.setText("Database Comparision");
        btnOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOneMouseClicked(evt);
            }
        });

        btnTwo.setBackground(new java.awt.Color(102, 102, 102));
        btnTwo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTwo.setForeground(new java.awt.Color(255, 255, 255));
        btnTwo.setText("Query Builder");
        btnTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTwoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnOne, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTwo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(572, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(leftPanel);

        rightPanel.setBackground(new java.awt.Color(0, 0, 255));
        rightPanel.setForeground(new java.awt.Color(255, 255, 255));
        rightPanel.setPreferredSize(new java.awt.Dimension(1366, 768));

        descLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        descLb.setForeground(new java.awt.Color(255, 255, 255));
        descLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descLb.setText("Welcome to the Utility");

        startBtn.setBackground(new java.awt.Color(102, 102, 102));
        startBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        startBtn.setForeground(new java.awt.Color(255, 255, 255));
        startBtn.setText("Proceed");
        startBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                        .addGap(0, 828, Short.MAX_VALUE)
                        .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)))
                .addContainerGap())
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descLb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 665, Short.MAX_VALUE)
                .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jSplitPane1.setRightComponent(rightPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOneMouseClicked
        // TODO add your handling code here:
        descLb.setText("Welcome to Data Comparision Mode");
        startBtn.setVisible(true); 
        String value  = descLb.getText();
        if(jframeDCObj.isVisible() && value.equals("Welcome to Data Comparision Mode"))
        {
            jframeDCObj.setState(java.awt.Frame.NORMAL);
            jframeDCObj.toFront();
            jframeDCObj.repaint();
        }
          
        
    }//GEN-LAST:event_btnOneMouseClicked

    private void btnTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTwoMouseClicked

        descLb.setText("Welcome to Query Builder Mode");
        startBtn.setVisible(true);
        String value = descLb.getText();
        if(jframeQBObj.isVisible() && value.equals("Welcome to Query Builder Mode"))
        {
            jframeQBObj.setState(java.awt.Frame.NORMAL);
            jframeQBObj.toFront();
            jframeDCObj.repaint();
        }
        
    }//GEN-LAST:event_btnTwoMouseClicked

    private void startBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startBtnMouseClicked
        // TODO add your handling code here:
         
          String value = descLb.getText();
          
        if(!jframeDCObj.isVisible() && value.equals("Welcome to Data Comparision Mode"))
        {
            jframeDCObj.setVisible(true);
        }
        if(jframeDCObj.isVisible() && value.equals("Welcome to Data Comparision Mode"))
        {
            jframeDCObj.setState(java.awt.Frame.NORMAL);
            jframeDCObj.toFront();
            jframeDCObj.repaint();
        }
        if(!jframeQBObj.isVisible() && value.equals("Welcome to Query Builder Mode"))
        {
            jframeQBObj.setVisible(true);
            
        }
        if(jframeQBObj.isVisible() && value.equals("Welcome to Query Builder Mode"))
        {
            jframeQBObj.setState(java.awt.Frame.NORMAL);
            jframeQBObj.toFront();
            jframeDCObj.repaint();
        }

        
    }//GEN-LAST:event_startBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(screenOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(screenOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(screenOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(screenOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new screenOne().setVisible(true);
                String postgreSQLPath = "C:\\AlphaUtility\\PostgreSQLConnections";
                File postgreSQLObj = new File(postgreSQLPath);
                if(!postgreSQLObj.exists())
                {
                    postgreSQLObj.mkdir();
                    System.out.println("Folder created Successfully for PostgreSQLDB");
                }
                String mongoDBPath = "C:\\AlphaUtility\\MongoDBConnections";
                File mongoDBObj = new File(mongoDBPath);
                if(!mongoDBObj.exists())
                {
                    mongoDBObj.mkdir();
                    System.out.println("Folder created Successfully for MongoDB");
                }
                String oracleDBPath = "C:\\AlphaUtility\\OracleDBConnections";
                File oracleDBObj = new File(oracleDBPath);
                if(!oracleDBObj.exists())
                {
                    oracleDBObj.mkdir();
                    System.out.println("Folder created Successfully for OracleDB");
                } 
                

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnTwo;
    private javax.swing.JLabel descLb;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton startBtn;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
